### ISSUE TITLE
All_phyto ID column

### ISSUE THREAD

**Issue by xdrl20aq** [ursho2552/Biomes_PROOCE#3]
in main.m:
```

% =========================================================================
% Delete first column to define an ID. Check if this is still needed!!
% =========================================================================

All_phyto(:,1) = [];
All_phyto(:,1) = 1:size(All_phyto,1);
labels_phyto(1) = [];
......
% =========================================================================
% Only consider complete rows, i.e. delete rows where we find a NaN for any
% species (i.e. only complete communities allowed)
% =========================================================================

for i =1:size(All_phyto,2)
    tmp = isnan(All_phyto(:,i));
    All_phyto(tmp == 1,:) = [];
end
% =========================================================================
% All_phyto now has no NaNs and the following structure
% ID|Lon|Lat|month|species1....n|buffer. Currently, the buffer space is 
% not used.
% =========================================================================

No_nan_phyto = [All_phyto(:,[1 3 4]),All_phyto(:,2),...
    All_phyto(:,5:end), (1:length(All_phyto))'*NaN];

```

Firstly the id column is defined and then some rows are deleted, which means the id column in No_nan_phyto(and later, No_nan_phyto_simple) should be "incomplete". However, when I load No_nan_phyto_simple, I found the values in id column start from 1.  Since Simple_sort_data.mat (which contains No_nan_phyto_simple) is the file for training SOM, does this issue have any potential effect?

**Comment by ursho2552** [comment]
The No_nan_phyto_simple is created further down. The point here is that instead of latitude and longitude, we get the coordinates directly of the xy-mesh for plotting. In the end, I don't think the ID was used. So it should be fine, particularly, since the SOM only looks at the species presence/absences and never at their location.

**Comment by xdrl20aq** [comment]
> The No_nan_phyto_simple is created further down. The point here is that instead of latitude and longitude, we get the coordinates directly of the xy-mesh for plotting. In the end, I don't think the ID was used. So it should be fine, particularly, since the SOM only looks at the species presence/absences and never at their location.

No_nan_phyto_simple is created from Transformed_phyto, which is from No_nan_phyto, so they have the same id column, right?  I think this ID column does matter in Validation.m 
```
        ind = No_nan_phyto_simple(training_flag == 0,1); 
        ind_tr = No_nan_phyto_simple(training_flag == 1,1);

        tmp_simple = No_nan_phyto_simple(:,2:4);
        tmp_simple(ind,:) = [];
```

If No_nan_phyto_simple's id column is incomplete after excluding rows with NAs, max(ind) should be around 700000, which results in error in  tmp_simple(ind,:) = [], because after excluding tmp_simple (created from No_nan_phyto_simple) only has ~350000 rows. 
I add two lines in main.m to re-define id, and now it seems to work.

```
% =========================================================================
% All_phyto now has no NaNs and the following structure
% ID|Lon|Lat|month|species1....n|buffer. Currently, the buffer space is 
% not used.
% =========================================================================

No_nan_plankton = [All_plankton(:,1:end), (1:length(All_plankton))'*NaN];
id_column2 = 1:size(No_nan_plankton,1);
No_nan_plankton = [id_column2',No_nan_plankton];
```

**Comment by ursho2552** [comment]
Yes, you are right, so now the ID is also the entry number. For the validation, it just means that the ID number does not conform to the row number, but the training and testing split is still ok, since it takes consistently the same indeces.

So overall, your version is clearer. I will change it

**Comment by xdrl20aq** [comment]
> Yes, you are right, so now the ID is also the entry number. In fact, if you can check my "No_nan_pytho_simple" stored in my directory, you can see that I have 341'646 unique IDs starting from 1 up to 341'647. My guess is, this step got lost during the cleaning of the code.
> 
> So overall, your approach solves the problem, but rather than appending a new column, you should overwrite the first one. Otherwise, you will get into trouble when training the SOM, since the function takes the columns 5 until end-1 for the training.

Indeed. Thanks!
