### ISSUE TITLE
monthly biome gif

### ISSUE THREAD

**Issue by siiyizhang** [ursho2552/Biomes_PROOCE#4]
Hi Urs, the monthly biome gif you showed here might be wrong. According to Table A.8 in your paper, (4) SUS should be absent from November to March, but here it is present throughout the year.

**Comment by ursho2552** [comment]
Hi Siyi, the numbers given in Table A.8 indeed show that the SUS biome is not present in some months. However, we specify on the caption that "the Southern Hemisphere was shifted by six months", i.e., the mean area coverage was calculated using the seasonally corrected monthly biomes. By doing this, we can e.g. show that the SUS (SUmmer Subtropical) biome is present and at it's largest during the global summer, and the WIS (WInter Subtropical) biome is absent during global summer but present in the colder months of each Hemisphere.

The gif, however, was created using the monthly biomes without the seasonal correction.

Hope this information helps clarify the differences between the gif and the data shown in the paper.

**Comment by xdrl20aq** [comment]
I see. Thanks for the explanation!
